<?php

namespace MPM\EntityBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AlumnoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlumnoRepository extends EntityRepository
{
    public function findByInicial($inicail)
    {
        $this->getEntityManager()
            ->createQuery(
                'SELECT a FROM EntityBundle:Alumno a WHERE a.apellido LIKE %s ORDER BY a.apellido ASC'
            )
            ->setParameter('%s' ,$inicail . '%')
            ->getResult();

    }
}
