<?php

namespace MPM\EntityBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ConversacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConversacionRepository extends EntityRepository
{
}
