<?php

namespace MPM\EntityBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TutorRelationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TutorRelationRepository extends EntityRepository
{
}