main_homepage:
    pattern:  /
    defaults: { _controller: MainBundle:Home:index }


login:
    pattern:  /login
    defaults: { _controller: MainBundle:Security:login }
login_check:
    path:  /login_check
logout:
    path:  /logout