security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_SECRETARIA:  ROLE_USER
        ROLE_ADMIN:       ROLE_SECRETARIA
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        in_memory:
            memory:
                users:
                    User:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    Secretaria:  { password: secpass, roles: [ 'ROLE_SECRETARIA' ] }
                    Admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        main:
            pattern:    ^/
            form_login:
                check_path: login_check
                login_path: login
            logout:
                path:   /logout
                target: /
            remember_me:
                key:      "%secret%"
                lifetime: 31536000 # 365 days in seconds
                path:     /
                domain:   ~ # Defaults to the current domain from $_SERVER
            anonymous: ~

    access_control:
        - { path: ^/secretaria, roles: ROLE_SECRETARIA }
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }