parameters:
#    teachers.example.class: MPM\TeachersBundle\Example

services:
#    teachers.example:
#        class: %teachers.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
