secretaria_homepage:
    pattern:  /
    defaults: { _controller: SecretariaBundle:Main:index }

secretaria_gestion_ref:
    resource: "@SecretariaBundle/Resources/config/routing/gestion.yml"
    prefix:   /gestion