parameters:
#    secretaria.example.class: MPM\SecretariaBundle\Example

services:
#    secretaria.example:
#        class: %secretaria.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
